# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seda/ClionProjects/UPS-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seda/ClionProjects/UPS-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seda/ClionProjects/UPS-server/CMakeFiles /home/seda/ClionProjects/UPS-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seda/ClionProjects/UPS-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UPS_server

# Build rule for target.
UPS_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UPS_server
.PHONY : UPS_server

# fast build rule for target.
UPS_server/fast:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/build
.PHONY : UPS_server/fast

gameRoom.o: gameRoom.cpp.o
.PHONY : gameRoom.o

# target to build an object file
gameRoom.cpp.o:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/gameRoom.cpp.o
.PHONY : gameRoom.cpp.o

gameRoom.i: gameRoom.cpp.i
.PHONY : gameRoom.i

# target to preprocess a source file
gameRoom.cpp.i:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/gameRoom.cpp.i
.PHONY : gameRoom.cpp.i

gameRoom.s: gameRoom.cpp.s
.PHONY : gameRoom.s

# target to generate assembly for a file
gameRoom.cpp.s:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/gameRoom.cpp.s
.PHONY : gameRoom.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/main.cpp.s
.PHONY : main.cpp.s

msgTable.o: msgTable.cpp.o
.PHONY : msgTable.o

# target to build an object file
msgTable.cpp.o:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/msgTable.cpp.o
.PHONY : msgTable.cpp.o

msgTable.i: msgTable.cpp.i
.PHONY : msgTable.i

# target to preprocess a source file
msgTable.cpp.i:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/msgTable.cpp.i
.PHONY : msgTable.cpp.i

msgTable.s: msgTable.cpp.s
.PHONY : msgTable.s

# target to generate assembly for a file
msgTable.cpp.s:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/msgTable.cpp.s
.PHONY : msgTable.cpp.s

players.o: players.cpp.o
.PHONY : players.o

# target to build an object file
players.cpp.o:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/players.cpp.o
.PHONY : players.cpp.o

players.i: players.cpp.i
.PHONY : players.i

# target to preprocess a source file
players.cpp.i:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/players.cpp.i
.PHONY : players.cpp.i

players.s: players.cpp.s
.PHONY : players.s

# target to generate assembly for a file
players.cpp.s:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/players.cpp.s
.PHONY : players.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/server.cpp.s
.PHONY : server.cpp.s

stl.o: stl.cpp.o
.PHONY : stl.o

# target to build an object file
stl.cpp.o:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/stl.cpp.o
.PHONY : stl.cpp.o

stl.i: stl.cpp.i
.PHONY : stl.i

# target to preprocess a source file
stl.cpp.i:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/stl.cpp.i
.PHONY : stl.cpp.i

stl.s: stl.cpp.s
.PHONY : stl.s

# target to generate assembly for a file
stl.cpp.s:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/stl.cpp.s
.PHONY : stl.cpp.s

timer.o: timer.cpp.o
.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i
.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s
.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/UPS_server.dir/build.make CMakeFiles/UPS_server.dir/timer.cpp.s
.PHONY : timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... UPS_server"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gameRoom.o"
	@echo "... gameRoom.i"
	@echo "... gameRoom.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... msgTable.o"
	@echo "... msgTable.i"
	@echo "... msgTable.s"
	@echo "... players.o"
	@echo "... players.i"
	@echo "... players.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... stl.o"
	@echo "... stl.i"
	@echo "... stl.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

